### ISSUE TITLE
Feature: "extra" field for Items to store, e.g. http-method to use, other style info ...

### ISSUE THREAD

**Issue by fwolfst** [adamcooke/actionnav#5]
Although I am likely to be against any "dump whatever you need here"-attributes, an `Item#extra` or `Item#meta` attribute would be really helpful, to cover e.g. additional style hints (we mix presentation and logic here, but `icon` does that already) or indication which http method to use on a specific link.

How would you like the API to look like? Want to specify it via some tests/specs in a branch and I give it a go?

**Comment by adamcooke** [comment]
This has been added

**Comment by fwolfst** [comment]
Thanks a bunch :) I see I have two more tickets from the same period open ;)
I hope to get to see a project where I can use actionnav again.
